# defaults:
#   - override hydra/sweeper: optuna
#   - override hydra/sweeper/sampler: tpe

# hydra:
#   sweeper:
#     sampler:
#       seed: 2137
#       consider_magic_clip: true
#     direction: maximize
#     study_name: minigrid
#     storage: null
#     n_trials: 100
#     n_jobs: 1
#     max_failure_rate: 0.0
#     params:
#       lr: range(1e-4, 1e-3, 1e-4)

dataset: "pubmed"
seed: 2138
epochs: 50
lr: 1e-2
hidden_channels: 256